# Generated by Django 2.2.7 on 2019-11-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='malzemeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malzemeid', models.CharField(max_length=50)),
                ('malzeme_text', models.CharField(max_length=200)),
                ('miktar', models.IntegerField(default=0)),
            ],
        ),
    ]
