# Generated by Django 2.2.7 on 2019-11-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myKitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('stext', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='material_groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('stext', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stext', models.CharField(max_length=200)),
                ('minstock', models.IntegerField(default=0)),
                ('endday', models.IntegerField(default=0)),
                ('openendday', models.IntegerField(default=0)),
                ('createdat', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='quantity_units',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('stext', models.CharField(max_length=200)),
                ('createdat', models.DateTimeField()),
            ],
        ),
    ]
