# Generated by Django 2.2.7 on 2019-11-13 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myKitchen', '0002_locations_material_groups_materials_quantity_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='stocktype',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
