# Generated by Django 2.2.7 on 2019-11-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myKitchen', '0003_materials_stocktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='stocktype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
