# Generated by Django 2.2.7 on 2019-11-14 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myKitchen', '0006_auto_20191114_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='qunit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myKitchen.Quantity_Units'),
        ),
    ]
