# Generated by Django 2.2.7 on 2019-11-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myKitchen', '0007_auto_20191114_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='qunit_id',
            new_name='qunit',
        ),
        migrations.AddField(
            model_name='materials',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myKitchen.Locations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='material_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myKitchen.Material_Groups'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materials',
            name='qunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myKitchen.Quantity_Units'),
        ),
    ]
